name       : perl-list-moreutils-xs
version    : '0.430'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-XS-0.430.tar.gz : e8ce46d57c179eecd8758293e9400ff300aaf20fefe0a9d15b9fe2302b9cb242
homepage   : https://metacpan.org/pod/List::MoreUtils::XS
license    : Apache-2.0
component  : programming.perl
summary    : List::MoreUtils::XS - Provide compiled List::MoreUtils functions
description: |
    List::MoreUtils::XS is a backend for List::MoreUtils. Even if it's possible (because of user wishes) to have it practically independent from List::MoreUtils, it technically depend on List::MoreUtils. Since it's only a backend, the API is not public and can change without any warning.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
