name       : perl-list-moreutils-xs
version    : '0.428'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-XS-0.428.tar.gz : 9d9fe621429dfe7cf2eb1299c192699ddebf060953e5ebdc1b4e293c6d6dd62d
license    : Apache-2.0
component  : programming.perl
summary    : Provide compiled List::MoreUtils functions
description: |
    Provide compiled List::MoreUtils functions
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
